web/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('face/', include('face.urls'))
]

web/app/face/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<url_id>', views.delete, name='delete'),
]

web/app/face/models.py
from django.db import models


class Url(models.Model):
    image_url = models.CharField(max_length=200)


class BoundingBox(models.Model):
    top = models.DecimalField(decimal_places=3, max_digits=5)
    right = models.DecimalField(decimal_places=3, max_digits=5)
    bottom = models.DecimalField(decimal_places=3, max_digits=5)
    left = models.DecimalField(decimal_places=3, max_digits=5)
    image = models.ForeignKey(Url, on_delete=models.CASCADE)

web/app/face/views.py
from django.shortcuts import render, redirect
from . import models
import cv2
from imutils import url_to_image

face_cascade = cv2.CascadeClassifier('/haarcascade_frontalface_default.xml')


def index(request):
    if request.method == 'POST':
        url = models.Url.objects.create(
            image_url=request.POST.get('image_url', ''))

        img = url_to_image(request.POST.get('image_url', ''))
        ih, iw, _ = img.shape
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        url.save()

        for (x, y, w, h) in faces:
            top = round(y * 100 / ih, 2)
            right = round((iw - x - w) * 100 / iw, 2)
            left = round(x * 100 / iw, 2)
            bottom = round((ih - y - h) * 100 / ih, 2)
            bb = models.BoundingBox.objects.create(top=top,
                                                   right=right,
                                                   left=left,
                                                   bottom=bottom,
                                                   image=url)
            bb.save()

        return redirect('/face')

    urls = models.Url.objects.all()
    context = {'image_urls': urls}
    return render(request, 'face/index.html', context)


def delete(request, url_id):
    item = models.Url.objects.get(pk=url_id)
    item.delete()
    return redirect('/face')

web/app/face/templates/face/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'face/style.css' %}">
    <title>Face App</title>
</head>
<body>
    <div class="wrapper">
        <form action="" method="post">
            <input type="text" name="image_url">
            <input type="submit">
            {% csrf_token %}
        </form>
        <div class="galery">
            {% if image_urls %}
            
            {% for image_url in image_urls %}
            <div class="image-container">
                <img src="{{ image_url.image_url }}">
                {% for bb in image_url.boundingbox_set.all %}
                    <div class="bounding-box" style="top: {{ bb.top }}%; right: {{ bb.right }}%; bottom: {{ bb.bottom }}%; left: {{ bb.left }}%;"></div>
               
                {% endfor %}
                <a href="{% url 'delete' image_url.id %}" class="btn-delete">delete</a>
            </div>
            {% endfor %}
            
            {% else %}
                <p>No images.</p>
            {% endif %}
        </div>
    </div>
</body>
</html>